services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/java:21-jdk-bullseye
    init: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ..:/home/vscode/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
    working_dir: /home/vscode/workspace
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: sample-db
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd!
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network: